#"#{} permet d'executer du code dans le text"
puts "On va compter le nombre d'heures de travail à THP"
#"le text"
puts "Travail : #{10 * 5 * 11}"
#"pour le temps de travail on fait la calcule 10*5*11=550"
puts "En minutes ça fait : #{10 * 5 * 11 * 60}"
#"pour le temps de travail en minutes on fait la calcule 10*5*11*60="
puts "Et en secondes ?"
#"le text"
puts 10 * 5 * 11 * 60 * 60
#"la resultat de "10 * 5 * 11 * 60 * 60"
puts "Est-ce que c'est vrai que 3 + 2 < 5 - 7 ?"
#"comparateur de taille"
puts 3 + 2 < 5 - 7
#"le text"
puts "Ça fait combien 3 + 2 ? #{3 + 2}"
puts "Ça fait combien 5 - 7 ? #{5 - 7}"
#"les valeurs de 3+2 et de 5-7"
puts "Ok, c'est faux alors !"
#"text"
puts "C'est drôle ça, faisons-en plus :"

puts "Est-ce que 5 est plus grand que -2 ? #{5 > -2}"
puts "Est-ce que 5 est supérieur ou égal à -2 ? #{5 >= -2}"
puts "Est-ce que 5 est inférieur ou égal à -2 ? #{5 <= -2}"
#"comparateur comme dans la ligne 12"